import {walletTransfer} from '../src/receipt.js';
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import ganache from 'ganache';
import solc from 'solc';
import {BrowserProvider,ContractFactory,parseEther,ZeroAddress,MaxUint256} from 'ethers';
import {readFileSync} from 'node:fs';
import '../scripts/compile.mjs';
import {SEEDS,POTIONS,FORMS,rarityForRoll,specimen,rewardAmount,INITIAL_RESERVE,quoteArca,MIN_EXCHANGE_WEI,MAX_EXCHANGE_WEI} from '../src/world.js';
const artifact=JSON.parse(readFileSync(new URL('../src/arcana-contract.json',import.meta.url)));
const U=10n**18n;
let rpc,provider,alice,bob,garden;
before(async()=>{rpc=ganache.provider({logging:{quiet:true},chain:{chainId:1337,hardfork:'shanghai'},wallet:{totalAccounts:8}});provider=new BrowserProvider(rpc);provider.pollingInterval=10;[alice,bob]=await Promise.all([provider.getSigner(0),provider.getSigner(1)]);});
after(async()=>{await provider.destroy();await rpc.disconnect();});
async function fresh(a=artifact){garden=await new ContractFactory(a.abi,a.bytecode,alice).deploy();await garden.waitForDeployment();}
async function mine(n=1){for(let i=0;i<n;i++)await rpc.request({method:'evm_mine',params:[]});}
async function send(tx){return(await tx).wait();}
async function tokens(signer,need){const a=await signer.getAddress();if(!await garden.starterClaimed(a))await send(garden.connect(signer).claimStarter());for(let i=2;await garden.balanceOf(a)<need;i++){const d=await provider.getSigner(i),da=await d.getAddress();if(!await garden.starterClaimed(da))await send(garden.connect(d).claimStarter());const missing=need-await garden.balanceOf(a),b=await garden.balanceOf(da);await send(garden.connect(d).transfer(a,missing<b?missing:b));}}
async function grow(species=0,tier=0,infusion=0,signer=alice){await tokens(signer,await garden.potionPrice(tier));const g=garden.connect(signer),id=await garden.flowerCount();await send(g.plantSeed(species));await send(g.buyPotions(tier,infusion,1));await send(g.waterFlower(id,tier,infusion));await mine(3);return id;}
async function sell(id,signer=alice){const q=await garden.previewBloom(id);return send(garden.connect(signer).sellToPip(id,q.reward));}
async function solvent(){const a=await garden.getAddress();assert.equal(await garden.balanceOf(a),await garden.poolReserve()+await garden.siteRevenue()+await garden.totalClaims());assert.ok(await garden.poolReserve()>=await garden.reservedRewards());}

test('one-time initial reserve, operator identity and 100 ARCA grants match deployed bytecode',async()=>{
 await fresh();const a=await alice.getAddress();assert.equal(await garden.operator(),a);assert.equal(await garden.poolReserve(),INITIAL_RESERVE);assert.equal(await garden.balanceOf(a),0n);await send(garden.claimStarter());assert.equal(await garden.balanceOf(a),100n*U);assert.equal(await garden.totalSupply(),INITIAL_RESERVE+100n*U);await assert.rejects(garden.claimStarter.staticCall());assert.equal((await provider.getCode(await garden.getAddress())).toLowerCase(),artifact.deployedBytecode.toLowerCase());await solvent();
});
test('five free seeds remain owned and cannot sell before watering',async()=>{
 await fresh();for(let sp=0;sp<5;sp++){await send(garden.plantSeed(sp));assert.equal((await garden.flowers(sp)).species,BigInt(sp));assert.equal((await garden.previewBloom(sp)).ready,false);}assert.equal(await garden.gardenSize(await alice.getAddress()),5n);await assert.rejects(garden.plantSeed.staticCall(5));await assert.rejects(garden.plantSeed.staticCall(0,{value:1}));await assert.rejects(garden.sellToPip.staticCall(0,0));
});
test('purchases split 10/90 without burning, lock maximum payouts and validate inventory',async()=>{
 await fresh();await tokens(alice,200n*U);const supply=await garden.totalSupply(),a=await alice.getAddress();const r=await send(garden.buyPotions(0,2,2));assert.equal(await garden.balanceOf(a),80n*U);assert.equal(await garden.totalSupply(),supply);assert.equal(await garden.potions(a,0,2),2n);assert.equal(await garden.siteRevenue(),12n*U);assert.equal(await garden.poolReserve(),INITIAL_RESERVE+108n*U);assert.equal(await garden.reservedRewards(),800n*U);assert.equal(await garden.availableReserve(),INITIAL_RESERVE-692n*U);const split=r.logs.map(l=>{try{return garden.interface.parseLog(l);}catch{return null;}}).find(e=>e?.name==='PurchaseSplit');assert.equal(split.args.siteFee,12n*U);for(const args of [[4,0,1],[0,3,1],[0,0,0],[0,0,21],[3,0,1]])await assert.rejects(garden.buyPotions.staticCall(...args));await assert.rejects(garden.buyPotions.staticCall(0,0,1,{value:1}));await solvent();
});
test('watering consumes one owned bottle and cannot reroll or charge ARCA twice',async()=>{
 await fresh();await tokens(alice,120n*U);await send(garden.plantSeed(3));await send(garden.buyPotions(0,1,2));await assert.rejects(garden.connect(bob).waterFlower.staticCall(0,0,1));await assert.rejects(garden.waterFlower.staticCall(0,0,0));const before=await garden.balanceOf(await alice.getAddress());await send(garden.waterFlower(0,0,1));assert.equal(await garden.balanceOf(await alice.getAddress()),before);assert.equal(await garden.potions(await alice.getAddress(),0,1),1n);await assert.rejects(garden.waterFlower.staticCall(0,0,1));await mine(3);const q=await garden.previewBloom(0);assert.equal(q.ready,true);await mine(3);assert.equal((await garden.previewBloom(0)).rarity,q.rarity);assert.equal(await garden.reservedRewards(),800n*U);await solvent();
});
test('sale pays the full quote from reserve without minting, supports exact partial withdrawals',async()=>{
 await fresh();const id=await grow(4),q=await garden.previewBloom(id),a=await alice.getAddress(),supply=await garden.totalSupply();await assert.rejects(garden.connect(bob).sellToPip.staticCall(id,0));await assert.rejects(garden.sellToPip.staticCall(id,q.reward+1n));await sell(id);assert.equal(await garden.totalSupply(),supply);assert.equal(await garden.poolReserve(),INITIAL_RESERVE+54n*U-q.reward);assert.equal(await garden.reservedRewards(),0n);assert.equal(await garden.claimable(a),q.reward);assert.equal(await garden.totalClaims(),q.reward);await assert.rejects(garden.sellToPip.staticCall(id,0));await assert.rejects(garden.connect(bob).claimPetals.staticCall(1));await assert.rejects(garden.claimPetals.staticCall(0));await assert.rejects(garden.claimPetals.staticCall(q.reward+1n));await send(garden.claimPetals(10n*U));assert.equal(await garden.balanceOf(a),50n*U);assert.equal(await garden.claimable(a),q.reward-10n*U);await send(garden.claimPetals(q.reward-10n*U));assert.equal(await garden.balanceOf(a),40n*U+q.reward);assert.equal(await garden.siteRevenue(),6n*U);await solvent();
});
test('only operator may withdraw earned fees; reserve and player claims stay protected',async()=>{
 await fresh();const id=await grow(0,0,0,bob);await sell(id,bob);const reserve=await garden.poolReserve(),credits=await garden.claimable(await bob.getAddress());await assert.rejects(garden.connect(bob).claimSiteRevenue.staticCall(1));await assert.rejects(garden.claimSiteRevenue.staticCall(0));await assert.rejects(garden.claimSiteRevenue.staticCall(6n*U+1n));await send(garden.claimSiteRevenue(2n*U));assert.equal(await garden.siteRevenue(),4n*U);await send(garden.claimSiteRevenue(4n*U));await assert.rejects(garden.claimSiteRevenue.staticCall(1));assert.equal(await garden.totalSiteRevenue(),6n*U);assert.equal(await garden.poolReserve(),reserve);assert.equal(await garden.claimable(await bob.getAddress()),credits);await send(garden.connect(bob).claimPetals(credits));await solvent();
});
test('committed reserves reject new purchases atomically; funding adds only transferred tokens',async()=>{
 const source=readFileSync(new URL('../contracts/ArcanaGarden.sol',import.meta.url),'utf8').replace('1_000_000 ether','350 ether');const out=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'ArcanaGarden.sol':{content:source}},settings:{optimizer:{enabled:true,runs:200},evmVersion:'shanghai',outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}})));const c=out.contracts['ArcanaGarden.sol'].ArcanaGarden;await fresh({abi:c.abi,bytecode:'0x'+c.evm.bytecode.object});await send(garden.claimStarter());await send(garden.buyPotions(0,0,1));await send(garden.connect(bob).claimStarter());await assert.rejects(garden.connect(bob).buyPotions.staticCall(0,0,1));assert.equal(await garden.balanceOf(await bob.getAddress()),100n*U);assert.equal(await garden.potions(await bob.getAddress(),0,0),0n);assert.equal(await garden.siteRevenue(),6n*U);const supply=await garden.totalSupply();await send(garden.connect(bob).fundReserve(50n*U));assert.equal(await garden.poolReserve(),454n*U);assert.equal(await garden.totalSupply(),supply);await assert.rejects(garden.fundReserve.staticCall(0));await solvent();
});
test('preserved mutations survive expiry; expired unsaved bloom uses Common quote',async()=>{
 await fresh();const idA=await grow(),idB=await grow(1),q=await garden.previewBloom(idA);await send(garden.connect(bob).revealBloom(idA));await mine(260);assert.equal((await garden.previewBloom(idA)).rarity,q.rarity);const expired=await garden.previewBloom(idB);assert.equal(expired.expired,true);assert.equal(expired.reward,40n*U);await assert.rejects(garden.sellToPip.staticCall(idB,60n*U));await sell(idB);assert.equal(await garden.reservedRewards(),400n*U);await solvent();
});
test('all 16 exact offers, expected economics, rarity boundaries and five art families match',async()=>{
 await fresh();for(let t=0;t<4;t++){assert.equal(await garden.potionPrice(t),BigInt([60,120,240,480][t])*U);assert.equal(POTIONS[t].price,[60,120,240,480][t]);for(let r=0;r<4;r++)assert.equal(await garden.rewardFor(t,r),rewardAmount(t,r));const expected=[7500n,2000n,400n,100n].reduce((v,n,r)=>v+n*rewardAmount(t,r),0n)/10000n;assert.equal(expected,BigInt(52*2**t)*U);}
 const hist=[0,0,0,0];for(let r=0;r<10000;r++)hist[rarityForRoll(r)]++;assert.deepEqual(hist,[7500,2000,400,100]);for(const [roll,r] of [[0,0],[7499,0],[7500,1],[9499,1],[9500,2],[9899,2],[9900,3],[9999,3]])assert.equal(await garden.rarityForRoll(roll),BigInt(r));await assert.rejects(garden.rarityForRoll(10000));await assert.rejects(garden.rewardFor(4,0));assert.equal(SEEDS.length,5);assert.equal(new Set(FORMS.flat()).size,20);for(let sp=0;sp<5;sp++)assert.equal(new Set([0,1,2,3].map(r=>specimen(sp,r))).size,4);
});
test('ERC-20 transfers and allowances cannot access protocol reserves',async()=>{
 await fresh();await send(garden.claimStarter());const a=await alice.getAddress(),b=await bob.getAddress();await assert.rejects(garden.transfer.staticCall(ZeroAddress,0));await assert.rejects(garden.transfer.staticCall(b,101n*U));await assert.rejects(garden.transferFrom.staticCall(await garden.getAddress(),a,1));await send(garden.approve(b,2n*U));await send(garden.connect(bob).transferFrom(a,b,U));assert.equal(await garden.allowance(a,b),U);await assert.rejects(garden.connect(bob).transferFrom.staticCall(a,b,2n*U));await send(garden.approve(b,MaxUint256));await send(garden.connect(bob).transferFrom(a,b,1));assert.equal(await garden.allowance(a,b),MaxUint256);await solvent();
});


test('ETH exchange quotes use exact wei, fixed rate and inclusive size limits',async()=>{
 await fresh();for(const wei of [MIN_EXCHANGE_WEI,parseEther('0.0006'),parseEther('0.001'),parseEther('0.001000000000000001'),MAX_EXCHANGE_WEI])assert.equal(await garden.quoteArca(wei),quoteArca(wei));assert.equal(await garden.quoteArca(parseEther('0.001')),100n*U);for(const wei of [0n,MIN_EXCHANGE_WEI-1n,MAX_EXCHANGE_WEI+1n]){await assert.rejects(garden.quoteArca(wei));assert.throws(()=>quoteArca(wei));}
});
test('paying ETH credits only buyer ARCA, rejects bad quotes and supports potion purchases',async()=>{
 await fresh();const value=parseEther('0.001'),a=await alice.getAddress(),addr=await garden.getAddress();await assert.rejects(garden.buyArca.staticCall(100n*U+1n,{value}));await assert.rejects(garden.buyArca.staticCall(0,{value:0}));await assert.rejects(alice.sendTransaction({to:addr,value}));assert.equal(await garden.ethRevenue(),0n);const r=await send(garden.buyArca(100n*U,{value}));assert.equal(await garden.balanceOf(a),100n*U);assert.equal(await garden.balanceOf(await bob.getAddress()),0n);assert.equal(await garden.totalSupply(),INITIAL_RESERVE+100n*U);assert.equal(await garden.poolReserve(),INITIAL_RESERVE);assert.equal(await garden.ethRevenue(),value);assert.equal(await garden.totalEthReceived(),value);const e=r.logs.map(l=>{try{return garden.interface.parseLog(l);}catch{return null;}}).find(e=>e?.name==='ArcaPurchased');assert.equal(e.args.keeper,a);assert.equal(e.args.ethPaid,value);assert.equal(e.args.arcaReceived,100n*U);await send(garden.buyPotions(0,0,1));assert.equal(await garden.balanceOf(a),40n*U);assert.equal(await garden.siteRevenue(),6n*U);await solvent();
});
test('operator ETH collection is bounded and leaves ARCA obligations intact',async()=>{
 await fresh();await send(garden.connect(bob).buyArca(100n*U,{value:parseEther('0.001')}));await send(garden.connect(bob).buyPotions(0,0,1));const pool=await garden.poolReserve(),locked=await garden.reservedRewards();await assert.rejects(garden.connect(bob).claimEthRevenue.staticCall(1));await assert.rejects(garden.claimEthRevenue.staticCall(0));await assert.rejects(garden.claimEthRevenue.staticCall(parseEther('0.002')));await send(garden.claimEthRevenue(parseEther('0.0004')));assert.equal(await garden.ethRevenue(),parseEther('0.0006'));await send(garden.claimEthRevenue(parseEther('0.0006')));await assert.rejects(garden.claimEthRevenue.staticCall(1));assert.equal(await garden.totalEthReceived(),parseEther('0.001'));assert.equal(BigInt(await rpc.request({method:'eth_getBalance',params:[await garden.getAddress(),'latest']})),0n);assert.equal(await garden.poolReserve(),pool);assert.equal(await garden.reservedRewards(),locked);await solvent();
});
test('failed operator ETH transfers revert accounting so receipts cannot be lost',async()=>{
 const source=readFileSync(new URL('../contracts/ArcanaGarden.sol',import.meta.url),'utf8')+'\ncontract RejectingOperator { ArcanaGarden public garden; constructor(){garden=new ArcanaGarden();} function collect(uint256 amount) external {garden.claimEthRevenue(amount);} }';const out=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'Test.sol':{content:source}},settings:{optimizer:{enabled:true,runs:200},evmVersion:'shanghai',outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}})));const c=out.contracts['Test.sol'].RejectingOperator;const op=await new ContractFactory(c.abi,'0x'+c.evm.bytecode.object,alice).deploy();await op.waitForDeployment();garden=new (await import('ethers')).Contract(await op.garden(),artifact.abi,alice);await send(garden.buyArca(100n*U,{value:parseEther('0.001')}));await assert.rejects(async()=>send(op.collect(parseEther('0.001'),{gasLimit:300000})));assert.equal(await garden.ethRevenue(),parseEther('0.001'));assert.equal(BigInt(await rpc.request({method:'eth_getBalance',params:[await garden.getAddress(),'latest']})),parseEther('0.001'));await solvent();
});

test('combined growth purchases, plants and waters a batch in one receipt, leaving selections off-chain',async()=>{
 await fresh();await send(garden.buyArca(1000n*U,{value:parseEther('0.01')}));const a=await alice.getAddress();const receipt=await send(garden.growFlowers(4,0,2,2));assert.equal(await garden.balanceOf(a),880n*U);assert.equal(await garden.flowerCount(),2n);assert.equal(await garden.potions(a,0,2),0n);assert.equal(await garden.siteRevenue(),12n*U);for(const id of [0,1]){const f=await garden.flowers(id);assert.equal(f.species,4n);assert.equal(f.watered,true);assert.equal(f.plantedBlock,BigInt(receipt.blockNumber));assert.equal(f.revealBlock,BigInt(receipt.blockNumber+2));}await assert.rejects(garden.growFlowers.staticCall(5,0,0,1));await assert.rejects(garden.growFlowers.staticCall(0,3,0,20));assert.equal(await garden.flowerCount(),2n);assert.equal(await garden.balanceOf(a),880n*U);await solvent();
});
test('sell-and-claim transfers this flower reward in the sale receipt, leaving other credits untouched',async()=>{
 await fresh();const old=await grow(),id=await grow(1);await sell(old);const a=await alice.getAddress(),credit=await garden.claimable(a),wallet=await garden.balanceOf(a),q=await garden.previewBloom(id);await assert.rejects(garden.connect(bob).sellAndClaim.staticCall(id,0));await assert.rejects(garden.sellAndClaim.staticCall(id,q.reward+1n));const receipt=await send(garden.sellAndClaim(id,q.reward));assert.equal(await garden.balanceOf(a),wallet+q.reward);assert.deepEqual(walletTransfer(receipt,garden.target,a),{received:q.reward,sent:0n,net:q.reward});assert.equal(await garden.claimable(a),credit);assert.equal(await garden.totalClaims(),credit);const transfers=receipt.logs.map(l=>{try{return garden.interface.parseLog(l);}catch{return null;}}).filter(e=>e?.name==='Transfer');assert.ok(transfers.some(e=>e.args.from.toLowerCase()===(garden.target).toLowerCase()&&e.args.to===a&&e.args.value===q.reward));await assert.rejects(garden.sellAndClaim.staticCall(id,0));await solvent();
});
test('planting with a purchased bottle costs no additional ARCA and fails atomically without a bottle',async()=>{
 await fresh();await send(garden.claimStarter());await send(garden.buyPotions(0,0,1));await send(garden.growFromSatchel(2,0,0));assert.equal(await garden.balanceOf(await alice.getAddress()),40n*U);assert.equal((await garden.flowers(0)).watered,true);await assert.rejects(async()=>send(garden.growFromSatchel(1,0,0,{gasLimit:500000})));assert.equal(await garden.flowerCount(),1n);await solvent();
});
