import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {emptyLedger,emptyAccount,change,UNIT,assertBacked,transact,readAccount,readLedger} from '../server/ledger.js';
import {depositAmount,tokenInterface,vaultInterface,TOKEN,domain,claimTypes,budgetDeployment} from '../server/chain.js';
import worker from '../server/worker.js';
import {Wallet,BrowserProvider,ContractFactory,parseEther,hexlify,randomBytes} from 'ethers';
import ganache from 'ganache';

function dbAdapter(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_thick_the_call.sql',import.meta.url),'utf8'));return {sql,prepare(q){return {args:[],bind(...args){this.args=args;return this;},async first(){return sql.prepare(q).get(...this.args)||null;},async run(){return sql.prepare(q).run(...this.args);},q};},async batch(stmts){sql.exec('BEGIN');try{const r=stmts.map(s=>sql.prepare(s.q).run(...s.args));sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
const base=()=>({l:{...emptyLedger(),vault:'0x'+'1'.repeat(40),backing:String(500n*UNIT)},a:emptyAccount()});
test('deployment uses a live EIP-1559 ceiling and checks actual balance before requesting approval',()=>{const q=budgetDeployment({balance:'9680572909946107',gas:'4402600',baseFee:'15',priority:'1000000',gasPrice:'1000015',value:'5000000000000000'});assert.equal(q.gasLimit,'5283120');assert.equal(q.maxFeePerGas,'2000030');assert.equal(q.maximumNetworkFee,'10566398493600');assert.equal(q.sufficient,true);assert.equal(budgetDeployment({balance:'5000000000000000',gas:'4402600',baseFee:'15',priority:'1000000',gasPrice:'1000015',value:'5000000000000000'}).sufficient,false);});
test('180 deposit → 60 potion → 40 sale leaves 160 in-game; partial payout preserves choice',()=>{const {l,a}=base();change(l,a,{kind:'deposit',amount:String(180n*UNIT)},0);change(l,a,{kind:'grow',id:'flower',species:4,tier:0,infusion:2,roll:100},0);assert.equal(a.balance,String(120n*UNIT));change(l,a,{kind:'sell',id:'flower'},9000);assert.equal(a.balance,String(160n*UNIT));change(l,a,{kind:'withdraw',nonce:'claim',amount:String(60n*UNIT),deadline:999},10000);assert.equal(a.balance,String(100n*UNIT));assert.equal(l.pending,String(60n*UNIT));change(l,a,{kind:'paid',nonce:'claim',hash:'paid'},11000);assert.equal(a.balance,String(100n*UNIT));change(l,a,{kind:'grow',id:'second',species:0,tier:0,infusion:0,roll:5},12000);assert.equal(a.balance,String(40n*UNIT));assertBacked(l);});
test('duplicate sale, early harvest, insufficient funds and unbacked legendary reserve are rejected',()=>{let {l,a}=base();assert.throws(()=>change(l,a,{kind:'grow',id:'a',species:0,tier:0,infusion:0,roll:0}),/Not enough/);({l,a}=base());change(l,a,{kind:'deposit',amount:String(60n*UNIT)});change(l,a,{kind:'grow',id:'a',species:0,tier:0,infusion:0,roll:9999},0);assert.throws(()=>change(l,a,{kind:'sell',id:'a'},1000),/still growing/);change(l,a,{kind:'sell',id:'a'},10000);assert.equal(a.balance,String(400n*UNIT));assert.throws(()=>change(l,a,{kind:'sell',id:'a'},10001),/already sold/);({l,a}=base());l.backing='0';change(l,a,{kind:'deposit',amount:String(60n*UNIT)});assert.throws(()=>change(l,a,{kind:'grow',id:'a',species:0,tier:0,infusion:0,roll:0}),/reserves/);});
test('atomic D1 writes prevent concurrent overspend and idempotent deposit replay',async()=>{const db=dbAdapter(),wallet='alice';await transact(db,{id:'setup',fingerprint:'s',wallet,event:{kind:'setup',vault:'vault',amount:String(1000n*UNIT)}});await Promise.all(Array.from({length:5},()=>transact(db,{id:'deposit',fingerprint:'d',wallet,event:{kind:'deposit',amount:String(60n*UNIT)}})));assert.equal((await readAccount(db,wallet)).balance,String(60n*UNIT));const r=await Promise.allSettled([1,2].map(i=>transact(db,{id:'grow'+i,fingerprint:'g'+i,wallet,event:{kind:'grow',id:'f'+i,species:0,tier:0,infusion:0,roll:1}})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await readAccount(db,wallet)).balance,'0');assert.equal((await readAccount(db,wallet)).flowers.length,1);assertBacked((await readLedger(db)).value);await assert.rejects(transact(db,{id:'deposit',fingerprint:'changed',wallet,event:{kind:'deposit',amount:String(999n*UNIT)}}),/already used/);db.sql.close();});
test('failed reservation leaves account and treasury unchanged; expiry releases only once',async()=>{const db=dbAdapter(),wallet='alice';await transact(db,{id:'d',fingerprint:'d',wallet,event:{kind:'deposit',amount:String(60n*UNIT)}});await assert.rejects(transact(db,{id:'g',fingerprint:'g',wallet,event:{kind:'grow',id:'f',species:0,tier:0,infusion:0,roll:1}}),/reserves/);assert.equal((await readAccount(db,wallet)).balance,String(60n*UNIT));await transact(db,{id:'w',fingerprint:'w',wallet,event:{kind:'withdraw',nonce:'n',amount:String(40n*UNIT),deadline:1}});await transact(db,{id:'x',fingerprint:'x',wallet,event:{kind:'expired',nonce:'n'}});await transact(db,{id:'x',fingerprint:'x',wallet,event:{kind:'expired',nonce:'n'}});assert.equal((await readAccount(db,wallet)).balance,String(60n*UNIT));db.sql.close();});
test('deposit proof rejects other tokens, other wallets and old flower-sale receipts',()=>{const wallet='0x'+'1'.repeat(40),vault='0x'+'2'.repeat(40);const log=tokenInterface.encodeEventLog(tokenInterface.getEvent('Transfer'),[wallet,vault,180n*UNIT]);assert.equal(depositAmount({logs:[{...log,address:TOKEN}]},vault,wallet),String(180n*UNIT));assert.throws(()=>depositAmount({logs:[{...log,address:'0x'+'3'.repeat(40)}]},vault,wallet),/no ARCA deposit/);assert.throws(()=>depositAmount({logs:[{...log,address:TOKEN}]},vault,'0x'+'4'.repeat(40)),/no ARCA deposit/);const sale=tokenInterface.encodeEventLog(tokenInterface.getEvent('Transfer'),[TOKEN,wallet,40n*UNIT]);assert.throws(()=>depositAmount({logs:[{...sale,address:TOKEN}]},vault,wallet),/no ARCA deposit/);});
test('wallet login verifies ownership, prevents nonce replay and hides unfinished mutation',async()=>{const db=dbAdapter(),user=Wallet.createRandom(),env={DB:db,ARCA_SIGNER_KEY:Wallet.createRandom().privateKey};let cookie='';const req=(path,body,origin='https://arcana.example')=>worker.fetch(new Request('https://arcana.example/api/'+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',origin,cookie},body:body?JSON.stringify(body):undefined}),env);assert.equal((await req('grow',{requestId:'invalid'})).status,401);const c=await(await req('auth/challenge',{wallet:user.address})).json();const signature=await user.signMessage(c.message);const login=await req('auth/verify',{id:c.id,signature});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];assert.match(login.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.equal((await req('auth/verify',{id:c.id,signature})).status,400);assert.equal((await req('grow',{},'https://evil.example')).status,403);const wallet=user.address.toLowerCase();await transact(db,{id:'s',fingerprint:'s',wallet,event:{kind:'setup',vault:'0x'+'1'.repeat(40),amount:String(500n*UNIT)}});await transact(db,{id:'d',fingerprint:'d',wallet,event:{kind:'deposit',amount:String(180n*UNIT)}});const body={requestId:'same-request-12345',species:1,tier:0,infusion:0};const g=await(await req('grow',body)).json(),replay=await(await req('grow',body)).json();assert.deepEqual(g,replay);let state=await(await req('state')).json();assert.equal(state.account.balance,String(120n*UNIT));assert.equal(state.account.flowers.length,1);assert.equal(state.account.flowers[0].rarity,null);assert.equal((await req('grow',{...body,tier:1})).status,400);db.sql.close();});

let rpc,provider,alice,bob,token,vault,service;
before(async()=>{rpc=ganache.provider({logging:{quiet:true},chain:{chainId:1337,hardfork:'shanghai'}});provider=new BrowserProvider(rpc);provider.pollingInterval=10;alice=await provider.getSigner(0);bob=await provider.getSigner(1);service=Wallet.createRandom();const ta=JSON.parse(readFileSync(new URL('../src/arcana-contract.json',import.meta.url))),va=JSON.parse(readFileSync(new URL('../src/vault-contract.json',import.meta.url)));token=await new ContractFactory(ta.abi,ta.bytecode,alice).deploy();await token.waitForDeployment();vault=await new ContractFactory(va.abi,va.bytecode,alice).deploy(await token.getAddress(),service.address,{value:parseEther('0.005')});await vault.waitForDeployment();});
after(async()=>{await provider?.destroy();await rpc?.disconnect();});
const send=async tx=>(await tx).wait();
test('real ERC20 deposit and payout are exactly two player transactions; gameplay changes no chain nonce',async()=>{await send(token.buyArca(parseEther('180'),{value:parseEther('0.0018')}));const wallet=await alice.getAddress(),address=await vault.getAddress();const nonce=await provider.send('eth_getTransactionCount',[wallet,'latest']);await send(token.transfer(address,parseEther('180')));const {l,a}=base();change(l,a,{kind:'deposit',amount:String(180n*UNIT)});change(l,a,{kind:'grow',id:'f',species:0,tier:0,infusion:0,roll:1},0);change(l,a,{kind:'sell',id:'f'},9000);assert.equal(BigInt(await provider.send('eth_getTransactionCount',[wallet,'latest'])),BigInt(nonce)+1n);assert.equal(await token.balanceOf(wallet),0n);const n=hexlify(randomBytes(32)),deadline=Math.floor(Date.now()/1000)+600,amount=BigInt(a.balance);const signature=await service.signTypedData({...domain(address),chainId:1337},claimTypes,{wallet,amount,nonce:n,deadline});await send(vault.withdraw(amount,n,deadline,signature));assert.equal(await token.balanceOf(wallet),160n*UNIT);assert.equal(BigInt(await provider.send('eth_getTransactionCount',[wallet,'latest'])),BigInt(nonce)+2n);await assert.rejects(vault.withdraw.staticCall(amount,n,deadline,signature),/revert|Used nonce/);});
test('withdrawal vouchers cannot be stolen, altered, replayed across vaults or used after expiry',async()=>{const wallet=await alice.getAddress(),address=await vault.getAddress(),nonce=hexlify(randomBytes(32)),amount=UNIT,deadline=Math.floor(Date.now()/1000)+600;const signature=await service.signTypedData({...domain(address),chainId:1337},claimTypes,{wallet,amount,nonce,deadline});await assert.rejects(vault.connect(bob).withdraw.staticCall(amount,nonce,deadline,signature));await assert.rejects(vault.withdraw.staticCall(amount+1n,nonce,deadline,signature));const bad=await service.signTypedData({...domain(await token.getAddress()),chainId:1337},claimTypes,{wallet,amount,nonce,deadline});await assert.rejects(vault.withdraw.staticCall(amount,nonce,deadline,bad));const expired=1,old=await service.signTypedData({...domain(address),chainId:1337},claimTypes,{wallet,amount,nonce,deadline:expired});await assert.rejects(vault.withdraw.staticCall(amount,nonce,expired,old));});
test('ETH top-up deposits directly to vault; reserve funding is distinctly labelled',async()=>{const wallet=await alice.getAddress(),before=await token.balanceOf(wallet),receipt=await send(vault.depositEth({value:parseEther('0.001')}));assert.equal(await token.balanceOf(wallet),before);const logs=receipt.logs.map(l=>{try{return vault.interface.parseLog(l);}catch{return null;}}).filter(Boolean);assert.equal(logs.find(l=>l.name==='EthDeposited').args.amount,100n*UNIT);assert.ok(!logs.some(l=>l.name==='ReserveFunded'));});
