import {gardenScene, SPECIES, INFUSIONS, potionFor, potionSVG, plantSVG} from './garden.js';
const options=()=>SPECIES.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');
const infusionOptions=()=>INFUSIONS.map(i=>`<option value="${i.id}">${i.name}</option>`).join('');
const initial=potionFor(500000000000000n);
export const page = `
<header class="site-header"><a class="brand" href="#"><img src="/favicon.svg" alt="" width="36" height="36"><span>Arcana<small>THE ENCHANTED CONSERVATORY</small></span></a><nav><a class="nav-active" href="#campaigns">The garden</a><a href="#alchemy">Alchemy desk</a><a href="#herbarium">Herbarium</a><button class="text-button" id="setup-open">Contract ↗</button></nav><button id="connect" class="button dark">Connect Wallet <span>↗</span></button></header>
<main>
<section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="dot"></span> A SANCTUARY FOR IMPOSSIBLE THINGS</div><h1>Some dreams<br>need a little <em>magic.</em></h1><p>Beyond the dreaming woods, a forgotten garden waits.<br>Plant an enchanted seed. Brew a little hope.<br>Let your collective magic bring it to life.</p><div class="hero-actions"><button id="create-open" class="button dark">✧ Plant a wish</button><a class="quiet-link" href="#alchemy">Visit the alchemy desk ↗</a></div><div class="hero-note"><span>SEPOLIA TESTNET</span><span>TEST ETH ONLY</span><span>NO PLATFORM FEE</span></div></div>
<aside class="garden-preview"><div class="preview-heading"><span class="eyebrow">THE MOONLIT CONSERVATORY</span><span class="preview-label">Practice realm · off-chain</span></div><div id="garden-scene" class="garden-scene">${gardenScene(0)}</div><div class="preview-bottom"><div><span class="preview-caption" id="preview-species-label">SPECIMEN 001 / MOONVEIL LILY</span><h2 id="preview-stage">A little magic lies dormant.</h2></div><button id="preview-water" class="button watering">Brew a potion ↗</button></div><div class="preview-progress"><span id="preview-fill"></span></div><div class="preview-meta"><span id="preview-hint">Practice goal: 0.005 test ETH · no wallet needed</span><button id="preview-reset" class="text-button">Reset specimen ↺</button></div></aside></section>
<section id="alchemy" class="alchemy"><div class="alchemy-heading"><div class="eyebrow">01 / THE ALCHEMIST’S WORKBENCH</div><h2>Something wondrous<br>is brewing.</h2><p>Measure your essence. Choose an infusion.<br>Discover the potion hidden in your contribution.</p><span class="practice-tag">✧ FREE PRACTICE · NO TRANSACTION</span></div><div class="brew-controls"><div class="form-grid"><label>Essence · test ETH<input id="brew-amount" type="number" min="0.000001" step="0.000001" value="0.0005"></label><label>Botanical specimen<select id="brew-species">${options()}</select></label></div><div class="dose-presets" aria-label="Practice essence amounts"><button data-dose="0.0001">0.0001</button><button data-dose="0.0005" class="selected">0.0005</button><button data-dose="0.001">0.001</button><button data-dose="0.002">0.002 ETH</button></div><label>Finish with an infusion<select id="brew-infusion">${infusionOptions()}</select></label><div class="brew-recipe" id="brew-recipe">Moonwell essence + Moon Salt</div><button class="button dark" id="brew-cast">Brew & cast · practice ✧</button><p id="brew-feedback" class="brew-feedback" role="status" aria-live="polite">The cauldron is yours. Try changing the amount.</p></div><div class="potion-display" id="brew-result" aria-live="polite"><span class="potion-tier">${initial.tier}</span>${potionSVG(initial)}<h3>${initial.name}</h3><span class="infusion-name">Lunar infusion</span><small>${initial.range}</small></div></section>
<div class="potion-key"><span>THE POTION GRIMOIRE</span><p><b>Whisperdew</b> &lt;0.0005</p><p><b>Moonwell</b> 0.0005–&lt;0.001</p><p><b>Starfire</b> 0.001–&lt;0.002</p><p><b>Phoenix</b> ≥0.002 <small>test ETH</small></p></div><p class="alchemy-note">Potion names follow the contribution amount. Infusions are cosmetic. Growth is proportional to test ETH contributed—no bonus multipliers or item purchases.</p>
<section class="connection-strip"><div><span class="dot" id="status-dot"></span><strong id="network-status">Outside the on-chain realm</strong><span id="wallet-address">Connect MetaMask to visit live gardens</span></div><a id="contract-link" target="_blank" rel="noreferrer" hidden>View Sepolia contract ↗</a></section>
<div id="notice" role="status" aria-live="polite" hidden></div>
<section class="stats"><div><span id="count">—</span><small>WISHES PLANTED</small></div><div><span id="raised">—</span><small>ESSENCE CONTRIBUTED · TEST ETH</small></div><div><span id="successful">—</span><small>CELESTIAL BLOOMS</small></div><div class="stat-note"><span>Rooted in a shared spell.</span><small>Each contribution leaves a trace on-chain.</small></div></section>
<section id="campaigns"><div class="section-heading"><div><div class="eyebrow">02 / THE LIVING GARDEN</div><h2>Where wishes take root.<span>✳</span></h2></div><button class="text-button" id="refresh">Refresh garden ↻</button></div><div class="garden-toolbar"><div class="filters" role="group" aria-label="Filter wishes"><button class="selected" data-filter="all">All wishes</button><button data-filter="active">Growing</button><button data-filter="mine">My seedlings</button><button data-filter="backed">My enchantments</button></div><span class="live-label"><span class="dot"></span> LIVE CONTRACT DATA</span></div><div id="cards" class="cards"></div><button id="more" class="button outline" hidden>Explore earlier wishes ↓</button></section>
<section id="herbarium" class="herbarium"><div class="section-heading"><div><div class="eyebrow">03 / NOTES FROM THE HERBARIUM</div><h2>Not all flowers belong to this world.</h2></div><span class="field-note">An illustrated field guide · not live campaigns</span></div><div class="species-grid">${SPECIES.map((s,i)=>`<article class="species-card"><div class="species-art">${plantSVG(4,s.id)}<span>0${i+1}</span></div><div><span class="eyebrow">${s.domain}</span><h3>${s.name}</h3><p>${s.note}</p><button class="text-button" data-specimen="${s.id}">Study at the alchemy desk ↗</button></div></article>`).join('')}</div></section>
<section class="growth-guide"><div><span class="eyebrow">THE FIVE AWAKENINGS</span><h3>From quiet seed to celestial bloom.</h3></div><div class="growth-path"><span><b>I</b>Dormant<small>0%</small></span><i>···</i><span><b>II</b>Awakening<small>&gt;0–&lt;25%</small></span><i>···</i><span><b>III</b>Foliage<small>25–&lt;75%</small></span><i>···</i><span><b>IV</b>Gathering<small>75–&lt;100%</small></span><i>···</i><span><b>V</b>Bloom<small>100%</small></span></div></section>
<section class="lower"><div id="activity"><div class="eyebrow">A CHRONICLE OF LITTLE MIRACLES</div><h2>The spellbook</h2><p class="muted">Transaction receipts from this browser. Every spell has a public trail.</p><div id="history"></div></div><div id="how"><div class="eyebrow">A GUIDE FOR NEW KEEPERS</div><h2>Your first enchantment.</h2><ol><li><b>Plant a wish</b><span>Choose a magical species, describe your project, and set a funding goal and deadline. Confirm its creation in MetaMask.</span></li><li><b>Brew a contribution</b><span>Your test ETH amount determines the potion. Choose a cosmetic infusion, then approve the contribution. Confirmed funding makes the plant grow.</span></li><li><b>Bloom, or return the essence</b><span>At the goal, the creator can withdraw. If the deadline passes without success, each contributor can claim their own refund.</span></li></ol></div></section>
<section class="explain"><div><div class="eyebrow">FANTASTICAL GARDEN. VISIBLE RULES.</div><h2>The magic has a method.</h2><p>A crowdfunding contract holds the test ETH. Plants and potions bring those public rules to life. No keeper can change the goal after planting.</p></div><details><summary>What is stored on-chain?</summary><p>Creator, title, story (including a species tag), goal, deadline, amount raised, backers, payouts and contributions. Plant growth and potion tiers are calculated from these amounts. Infusions and practice brews are visual only, not tokens or NFTs.</p></details><details><summary>What should an apprentice know?</summary><p>This is an unaudited classroom prototype on Sepolia. Transactions cost test ETH and need confirmation. Refunds require a claim and do not refund gas. The contract cannot verify project quality or control how withdrawn funds are used.</p></details></section>
</main><footer><a class="brand" href="#"><img src="/favicon.svg" width="28" height="28" alt="">Arcana</a><span>For the things that have yet to bloom.<small>THE ENCHANTED CONSERVATORY · SEPOLIA</small></span><a href="/SeedFund.sol" target="_blank" rel="noreferrer">Read the ancient rules ↗</a></footer>
<div id="celebration" class="celebration" role="status" aria-live="polite" hidden><span>✧</span><b id="celebration-title"></b><p id="celebration-copy"></p></div>
<dialog id="create-dialog"><form id="create-form"><div class="dialog-title"><div><div class="eyebrow">THE FIRST CHAPTER</div><h2>Plant an enchanted wish.</h2></div><button type="button" class="close" data-close="create-dialog" aria-label="Close">×</button></div><label>Name your wish<input name="title" required maxlength="80" placeholder="A sanctuary for midnight readers"></label><label>Choose a botanical species<select name="species">${options()}</select></label><label>The story behind your wish<textarea name="description" required maxlength="470" rows="3" placeholder="What will this project bring into the world?"></textarea></label><div class="form-grid"><label>Funding goal · test ETH<input name="goal" required type="number" min="0.000001" step="0.000001" value="0.005"></label><label>Time to bloom<select name="duration"><option value="1440">1 day</option><option value="10080">7 days</option><option value="43200">30 days</option><option value="10">10 minutes · demo</option><option value="1">1 minute · refund demo</option></select></label></div><div class="form-note">The title, species and story will be public on-chain. Planting creates a crowdfunding campaign and requires a MetaMask transaction.</div><button class="button dark" type="submit">Plant wish · approve in wallet ↗</button></form></dialog>
<dialog id="fund-dialog"><form id="fund-form"><div class="dialog-title"><div><div class="eyebrow">THE CONTRIBUTION CAULDRON</div><h2>Brew a little possibility.</h2></div><button type="button" class="close" data-close="fund-dialog" aria-label="Close">×</button></div><p id="fund-title"></p><input type="hidden" name="id"><div class="form-grid"><label>Essence · test ETH<input name="amount" required type="number" min="0.000001" step="0.000001" value="0.001"></label><label>Cosmetic infusion<select name="infusion">${infusionOptions()}</select></label></div><div id="fund-potion" class="fund-potion" aria-live="polite"></div><p id="fund-remaining" class="muted"></p><div id="fund-growth" class="form-note"></div><p class="muted">Casting contributes this test ETH to the campaign contract. A recipe is visual, not a purchased item. Gas is additional; growth follows the contributed amount.</p><button class="button dark" type="submit">Cast potion · approve in MetaMask ↗</button></form></dialog>
<dialog id="setup-dialog"><div class="dialog-title"><div><div class="eyebrow">OPEN THE GARDEN GATES</div><h2>Your Sepolia sanctuary.</h2></div><button class="close" data-close="setup-dialog" aria-label="Close">×</button></div><p>Connect MetaMask and deploy the garden contract on Sepolia. You need test ETH for gas. Your private key stays in your wallet.</p><button id="deploy" class="button dark">Deploy garden contract ↗</button><div class="divider">or connect an existing SeedFund contract</div><form id="address-form"><label>Contract address<input name="address" placeholder="0x…" required pattern="0x[a-fA-F0-9]{40}"></label><button type="submit" class="button outline">Enter this garden</button></form><p id="deployment-detail" class="muted"></p><button id="export" class="text-button" hidden>Download deployment record ↓</button><p class="muted">The address is saved in this browser. To share the same deployment, save the downloaded record as <code>src/deployment.json</code> and rebuild.</p><a href="/solidity-standard-input.json" download>Download source verification input ↓</a></dialog>`;
