import {BrowserProvider,Contract,ContractFactory,parseEther,formatEther} from 'ethers';
import {SEEDS,POTIONS,INFUSIONS,RARITIES,FORMS,specimen,growingArt,potionSVG,potion,quoteArca} from './world.js';
import vaultArtifact from './vault-contract.json';
import './game.css';
import './garden-v3.css';
import './session-game.css';

const BASE=import.meta.env.BASE_URL,API_ORIGIN=import.meta.env.VITE_API_ORIGIN||'',CROSS_ORIGIN=Boolean(API_ORIGIN&&API_ORIGIN!==location.origin);
let sessionToken='';try{if(CROSS_ORIGIN)sessionToken=sessionStorage.getItem('arcana:pages-session')||'';}catch{}
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const amount=n=>formatEther(BigInt(n||0)).replace(/\.0$/,''),short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'Not connected';
const TOKEN='0xc353a90e666E2C70279DC692FeEE7CB15AA8cB83',CHAIN='0xaa36a7';
const tokenAbi=['function transfer(address,uint256) returns(bool)','function balanceOf(address) view returns(uint256)'];
let state=null,selected=0,busy=false,provider,injected,walletBalance=null,selectedTier=0,selectedInfusion=0,lastFlowerMarkup='',lastArtSelection='',previewTimer,refreshing=false;
const providers=[];
window.addEventListener('eip6963:announceProvider',e=>{if(e.detail?.info?.rdns==='io.metamask')providers.push(e.detail.provider);});
window.dispatchEvent(new Event('eip6963:requestProvider'));

$('#app').innerHTML=`
<header class="arc-header"><a href="${BASE}" class="arc-brand">✧ <span>Arcana<small>THE ENCHANTED CONSERVATORY</small></span></a><nav><a href="#seed-library">Seed cabinet</a><a href="#bloom-atlas">Bloom atlas</a><a href="#my-garden">My garden</a><a href="#petal-purse">Petal purse</a></nav><button id="connect" class="button">Connect Wallet ↗</button></header>
<main class="arc-main">
<section class="arc-hero"><div><span class="eyebrow">A LITTLE MAGIC. A GARDEN OF YOUR OWN.</span><h1>Let your wonder<br><em>take root.</em></h1><p>Five curious seeds. A drop of moonlight. A bloom only you could discover.</p><a href="#seed-library" class="button">Choose your next seed ↓</a></div><div class="hero-blooms">${specimen(0,2)}${specimen(4,3)}<span>Grown with a little stardust ✦</span></div></section>
<div id="notice" role="status" aria-live="polite" hidden></div>
<section id="activation" class="activation" hidden><b>Our new garden is almost ready.</b><p>The settlement vault needs one-time activation. Your existing wallet ARCA and previous flowers are safe. Deposits and purchases stay paused until it is ready.</p><a href="${API_ORIGIN||BASE.slice(0,-1)}/onchain.html">Open your previous on-chain garden ↗</a></section>
<section id="petal-purse" class="purse-section"><div class="section-heading"><div><span class="eyebrow">YOUR PETAL PURSE</span><h2>Your petals. Your choice.</h2></div><span class="network-pill">✦ Sepolia testnet</span></div>
<div class="balance-pair"><article class="game-purse"><span class="eyebrow">IN YOUR GAME</span><div class="big-balance"><strong id="game-balance">—</strong><span>ARCA</span></div><p>Spend these petals on potions, or withdraw them to your wallet. Selling flowers adds to this balance.</p><div class="purse-actions"><button id="open-topup" class="button">Top up · ETH → ARCA ↗</button><a href="#seed-library" class="button secondary">Keep playing ✧</a><button id="open-withdraw" class="button secondary">Withdraw to wallet ↗</button></div><small id="game-session">Connect once to open your saved garden.</small></article>
<article class="wallet-purse"><span class="eyebrow">IN YOUR METAMASK WALLET</span><div class="big-balance"><strong id="wallet-balance">—</strong><span>ARCA</span></div><p id="wallet-address">Your existing tokens stay in your wallet until you choose to deposit them.</p><div class="purse-actions"><button id="open-deposit" class="button">Deposit existing ARCA ↗</button><button id="watch-token" class="text-button">Show ARCA in MetaMask</button></div><button id="refresh" class="text-button">Refresh balances ⟳</button></article></div>
<div class="how-it-flows"><span><b>01</b> Top up <small>Sepolia ETH → game ARCA</small></span><i>→</i><span><b>02</b> Keep & play <small>Saved ARCA · no wallet prompts</small></span><i>→</i><span><b>03</b> Withdraw <small>Game ARCA → wallet ARCA</small></span></div>
<p class="fine">1 Sepolia ETH = 100,000 ARCA. Top-up and withdrawal each require one MetaMask transaction plus network gas. Gameplay uses your saved ARCA. Withdraw any amount, keep the rest to play; withdrawals return ARCA, not ETH.</p><div id="pending-game-action" class="pending-box" hidden><b>A saved game action needs verification.</b><p>A connection interruption may have hidden the result. Retry the saved request to recover it without charging twice.</p><button id="retry-game-action" class="button secondary">Recover saved game action</button></div><div id="pending-withdrawal" class="pending-box" hidden></div><div id="receipt" class="receipt-box" hidden></div>
<details class="recovery"><summary>Recover a deposit or withdrawal · view token details</summary><p>Already confirmed a transaction? Verify it here. Never send it again just because a page did not refresh.</p><div class="recovery-row"><input id="recover-hash" aria-label="Transaction hash" placeholder="0x… transaction hash"><select id="recover-type" aria-label="Transfer type"><option value="deposit">Deposit</option><option value="withdraw">Withdrawal</option></select><button id="recover" class="button secondary">Verify receipt</button></div><p class="break">ARCA token: <a href="https://sepolia.etherscan.io/token/${TOKEN}" target="_blank" rel="noreferrer">${TOKEN}</a><br>Withdrawals deliver this same ARCA token. Sepolia ETH is only used for network gas or optional top-ups.</p></details>
</section>
<section id="seed-library"><div class="section-heading"><div><span class="eyebrow">THE SEED CABINET</span><h2>What will you awaken?</h2></div><span class="quiet-chip">Seed selection is free</span></div><div class="seed-cabinet">${SEEDS.map((s,i)=>`<button class="seed-choice ${i===0?'selected':''}" data-seed="${i}" aria-pressed="${i===0}"><div>${specimen(i,0,true)}</div><small>SEED 0${i+1}</small><h3>${s.name}</h3><p>${s.note}</p><span class="seed-status">${i===0?'Selected ✧':'Choose seed'}</span></button>`).join('')}</div>
<section id="bloom-atlas" class="bloom-atlas"><div class="section-heading"><div><span class="eyebrow">THE BLOOM ATLAS · FREE TO EXPLORE</span><h2 id="atlas-title">The many faces of Moonveil Lily.</h2></div><button id="preview-growth" class="text-button">Preview growth ✧</button></div><p class="fine">Choose any seed above to discover its four possible forms. These are illustrations, not flowers you own.</p><div id="bloom-forms" class="bloom-forms"></div><div id="growth-preview" class="growth-preview" hidden><div id="growth-preview-art"></div><p id="growth-preview-copy" role="status"></p></div></section>
<div class="potion-heading"><span class="eyebrow">THE APOTHECARY SHELF</span><h2>Pick a bottle of wonder.</h2><p class="fine">Previewing and choosing a bottle is free. ARCA is spent only when you press Plant & grow.</p></div><div id="potion-shelf" class="potion-shelf">${POTIONS.map((p,i)=>`<button class="potion-choice" data-potion="${i}" aria-pressed="${i===0}"><small>${p.tier}</small><div class="bottle-art">${potionSVG(potion(i,0))}<span class="bottle-seal">${['☽','✧','✦','♛'][i]}</span></div><h3>${p.name}</h3><p>${p.recipe}</p><b>${p.price} ARCA</b><span class="potion-selection">${i===0?'Selected ✧':'Choose potion'}</span></button>`).join('')}</div>
<div class="brew-bench"><div><span class="eyebrow">THE POTION BENCH</span><h2>A little alchemy.</h2><p id="seed-name">For your Moonveil Lily</p><small>One potion grows one flower. All purchases use your saved game balance.</small></div><div class="brew-controls"><label>Potion<select id="tier">${POTIONS.map((p,i)=>`<option value="${i}">${p.name} · ${p.price} ARCA</option>`).join('')}</select></label><label>Magical infusion<select id="infusion">${INFUSIONS.map((v,i)=>`<option value="${i}">${v.name}</option>`).join('')}</select></label><button id="grow" class="button">Plant & grow · 60 ARCA ✧</button><p id="purchase-hint">Uses game balance · no wallet transaction</p></div></div>
<div class="odds">${RARITIES.map((r,i)=>`<span><i style="background:${r.color}"></i>${esc(r.label)} <b>${[75,20,4,1][i]}%</b><small id="offer-${i}">${[40,60,150,400][i]} ARCA sale</small></span>`).join('')}</div><p class="fine">Potion prices include a 10% site fee. Mutations are drawn by the server; rarity odds are the same for every seed and potion. All possible payouts are reserved before a purchase.</p></section>
<section id="my-garden"><div class="section-heading"><div><span class="eyebrow">YOUR GROWING COLLECTION</span><h2>A garden full of possibilities.</h2></div><span id="flower-count" class="quiet-chip">0 flowers</span></div><div id="flowers" class="session-flowers"></div></section>
<section class="pip-market"><img src="${BASE}art/pip-flat.png" alt="Pip, your little magical pika merchant"><div><span class="eyebrow">PIP’S MOONLIGHT MARKET</span><h2>“I’ll take that lovely bloom!”</h2><p>Pip pays straight into your game purse. Nothing leaves for MetaMask until <em>you</em> choose Withdraw.</p><div id="sale-choice" hidden><b id="sale-message"></b><div class="purse-actions"><a class="button" href="#seed-library">Grow another flower ✧</a><button class="button secondary" id="sale-withdraw">Withdraw my petals ↗</button></div></div></div></section>
<section class="spellbook"><div class="section-heading"><div><span class="eyebrow">YOUR SPELLBOOK</span><h2>Every petal accounted for.</h2></div></div><div id="history"><p>Sign in to see your saved activity.</p></div></section>
<details class="setup" id="setup" hidden><summary>Operator · activate settlement</summary><p>This one-time deployment reuses the existing ARCA token. It does not replace anyone’s tokens. Initial reserve funds buybacks; it is not a personal game deposit.</p><label>Initial reserve funding (Sepolia ETH)<input id="setup-funding" value="0.005" inputmode="decimal"></label><p>0.005 test ETH funds 500 ARCA of reserves. Larger potion tiers remain paused until enough reserve is available. Deployment also uses gas.</p><p id="setup-quote" role="status">Current network fees will be checked before MetaMask opens.</p><button id="deploy-vault" class="button">Review settlement deployment ↗</button><details><summary>Register an already deployed vault</summary><input id="setup-address" aria-label="Vault address" placeholder="0x… vault address"><input id="setup-hash" aria-label="Deployment transaction" placeholder="0x… deployment transaction"><button id="register-vault" class="button secondary">Verify & activate</button></details></details>
<footer><a class="arc-brand" href="#">✧ Arcana</a><p>A Sepolia prototype. Game balances are server-managed and backed by ARCA held in the settlement vault. ARCA has no promised cash value.</p><div><a href="${API_ORIGIN||BASE.slice(0,-1)}/onchain.html">Previous on-chain garden</a><a href="${BASE}ArcanaVault.sol" target="_blank">Settlement Solidity</a><a id="vault-link" hidden target="_blank" rel="noreferrer">Vault on Sepolia ↗</a></div></footer>
</main>
<dialog id="transfer-dialog"><form method="dialog"><button class="dialog-close" aria-label="Close">×</button></form><span class="eyebrow" id="dialog-eyebrow">YOUR PETAL PURSE</span><h2 id="dialog-title"></h2><p id="dialog-copy"></p><label id="amount-label">Amount in ARCA<input id="transfer-amount" inputmode="decimal" autocomplete="off"></label><button id="max" class="text-button">Use maximum</button><p id="transfer-quote" class="fine"></p><button id="transfer-submit" class="button full"></button><button id="switch-deposit" class="text-button" hidden>Or top up using Sepolia ETH</button><p class="fine">Review the amount and network fee in MetaMask. Your balance updates after the transaction confirms.</p></dialog>`;

function notify(text,error=false){$('#notice').hidden=false;$('#notice').textContent=text;$('#notice').classList.toggle('error',error);}
function errorText(e){return e.code===4001||e.code==='ACTION_REJECTED'?'Declined in MetaMask. No new transaction was approved. Any reserved withdrawal stays available to retry.':e.shortMessage||e.message||'Please try again.';}
async function api(path,body) {const r=await fetch(API_ORIGIN+'/api/'+path,{method:body?'POST':'GET',headers:{...(body?{'content-type':'application/json'}:{}),...(CROSS_ORIGIN&&sessionToken?{authorization:'Bearer '+sessionToken}:{})},body:body?JSON.stringify(body):undefined,credentials:CROSS_ORIGIN?'omit':'same-origin'});const data=await r.json();if(!r.ok){const e=Error(data.error||'The garden is unavailable.');e.unchanged=data.unchanged;e.status=r.status;throw e;}if(CROSS_ORIGIN&&path==='auth/verify'&&data.sessionToken){sessionToken=data.sessionToken;try{sessionStorage.setItem('arcana:pages-session',sessionToken);}catch{}}return data;}
const requestKey=()=>`arcana:pending-game-request:${state?.wallet}`;
function savedRequest(){try{return JSON.parse(localStorage.getItem(requestKey())||'null');}catch{return null;}}
async function gameAction(path,fields){const existing=savedRequest();if(existing&&(existing.path!==path||JSON.stringify(existing.fields)!==JSON.stringify(fields)))throw Error('Recover the saved game action above before starting a different one.');const p=existing||{path,fields,body:{...fields,requestId:crypto.randomUUID()}};localStorage.setItem(requestKey(),JSON.stringify(p));try{const r=await api(p.path,p.body);localStorage.removeItem(requestKey());return r;}catch(e){if(e.unchanged)localStorage.removeItem(requestKey());throw e;}}
$('#retry-game-action').onclick=()=>action(async()=>{const p=savedRequest();if(!p)return;await gameAction(p.path,p.fields);notify('Saved action recovered. Your game balance has been synchronized; it was not charged twice.');});
async function action(fn){if(busy)return;busy=true;render();try{await fn();}catch(e){notify(errorText(e),true);}finally{busy=false;await refresh();}}
async function refresh(){if(refreshing)return;refreshing=true;try{const next=await api('state');if(next.wallet!==state?.wallet)walletBalance=null;state=next;render();}catch(e){notify('The garden could not be loaded. '+errorText(e),true);}finally{refreshing=false;}}
async function readWallet(){if(!state?.wallet)return;try{const r=await api('wallet',{});walletBalance=r.balance;$('#wallet-balance').textContent=amount(walletBalance);return true;}catch(e){walletBalance=null;$('#wallet-balance').textContent='Unavailable';notify(errorText(e),true);return false;}}
function getInjected(){injected=providers[0]||window.ethereum?.providers?.find(p=>p.isMetaMask)||window.ethereum;if(!injected)throw Error('Open this website in Chrome with MetaMask installed, or in the MetaMask browser.');return injected;}
async function signer(){const inj=getInjected();if(await inj.request({method:'eth_chainId'})!==CHAIN)await inj.request({method:'wallet_switchEthereumChain',params:[{chainId:CHAIN}]});provider=new BrowserProvider(inj);const s=await provider.getSigner();if(state?.wallet&&(await s.getAddress()).toLowerCase()!==state.wallet)throw Error('MetaMask has a different account selected. Switch to '+short(state.wallet)+' before transferring.');return s;}
$('#connect').onclick=()=>action(async()=>{const inj=getInjected();await inj.request({method:'eth_requestAccounts'});provider=new BrowserProvider(inj);const s=await provider.getSigner(),wallet=await s.getAddress();if(state?.wallet===wallet.toLowerCase()){await readWallet();notify('Your saved garden is open. Buying potions and selling flowers do not need MetaMask.');return;}const c=await api('auth/challenge',{wallet});notify('Sign in once to open your saved garden. This signature costs no gas and transfers no tokens.');const signature=await s.signMessage(c.message);await api('auth/verify',{id:c.id,signature});walletBalance=null;await refresh();await readWallet();notify('Garden opened. Gameplay uses your saved balance with no further wallet prompts.');});
$('#refresh').onclick=()=>action(async()=>{await refresh();const checked=await readWallet();if(checked)notify('Game balance and on-chain ARCA checked.');});
$('#watch-token').onclick=()=>action(async()=>{await signer();await injected.request({method:'wallet_watchAsset',params:{type:'ERC20',options:{address:TOKEN,symbol:'ARCA',decimals:18}}});notify('ARCA display request sent to MetaMask. Your token balance is checked independently on this page.');});
function render(){
  const a=state?.account,ready=Boolean(state?.vault&&a),balance=BigInt(a?.balance||0);
  $('#pending-game-action').hidden=!state?.wallet||!savedRequest();$('#retry-game-action').disabled=busy;
  $('#activation').hidden=Boolean(state?.vault)||!state;$('#connect').textContent=state?.wallet?short(state.wallet)+' · Signed in':'Connect Wallet ↗';
  $('#game-balance').textContent=a?amount(a.balance):'—';$('#wallet-balance').textContent=walletBalance===null?'—':amount(walletBalance);
  $('#wallet-address').textContent=state?.wallet||'Your existing tokens stay in your wallet until you choose to deposit them.';
  $('#game-session').textContent=state?.wallet?'Saved to your wallet’s game account · purchases need no MetaMask confirmation':'Connect once to open your saved garden.';
  $('#setup').hidden=state?.wallet!==state?.operator||Boolean(state?.vault);$('#vault-link').hidden=!state?.vault;if(state?.vault)$('#vault-link').href='https://sepolia.etherscan.io/address/'+state.vault;
  $('#open-deposit').disabled=busy||!ready;$('#open-topup').disabled=busy||!ready;
  $('#watch-token').disabled=busy||!state?.wallet;
  for(const id of ['open-withdraw','sale-withdraw'])$('#'+id).disabled=busy||!ready||balance===0n||a?.withdrawals.some(w=>w.status==='pending');
  $('#connect').disabled=busy;$('#refresh').disabled=busy;$('#grow').disabled=busy||!ready||balance<BigInt(POTIONS[selectedTier].price)*10n**18n;
  $('#grow').textContent=`Plant & grow · ${POTIONS[selectedTier].price} ARCA ✧`;
  const cost=BigInt(POTIONS[selectedTier].price)*10n**18n,max=BigInt(400*2**selectedTier)*10n**18n;
  const reserveLow=state?.reserve&&BigInt(state.reserve.free)+cost*9n/10n<max;
  if(reserveLow)$('#grow').disabled=true;
  $('#purchase-hint').textContent=!a?'Sign in once to open your game balance.':!state.vault?'Settlement activation pending. Existing wallet tokens are unchanged.':balance<cost?'Not enough game ARCA. Top up with Sepolia ETH, or deposit ARCA you already own.':reserveLow?'Pip needs more reserves for this potion. Your ARCA has not been spent.':`Uses game balance · no gas · ${POTIONS[selectedTier].price/10} ARCA site fee included`;
  $('#seed-name').textContent='For your '+SEEDS[selected].name;
  renderArtwork();
  document.querySelectorAll('[data-seed]').forEach(b=>{const yes=Number(b.dataset.seed)===selected;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));b.querySelector('.seed-status').textContent=yes?'Selected ✧':'Choose seed';});
  for(let i=0;i<4;i++)$('#offer-'+i).textContent=[40,60,150,400][i]*2**selectedTier+' ARCA sale';
  const flowers=a?.flowers||[];$('#flower-count').textContent=flowers.filter(f=>!f.sold).length+' flowers';
  const markup=flowers.slice().reverse().map(f=>{const ready=f.rarity!==null,phase=Date.now()-f.created>4500?2:1;
    return `<article class="session-flower ${f.sold?'sold':''}"><div class="session-art"><span class="flower-pill">${f.sold?'Sold to Pip':ready?esc(RARITIES[f.rarity].label):'Growing'}</span>${ready?specimen(f.species,f.rarity):growingArt(f.species,phase,f.infusion,f.tier)}</div><div class="flower-copy"><small>${esc(POTIONS[f.tier].name)}</small><h3>${esc(ready?FORMS[f.species][f.rarity]:SEEDS[f.species].name)}</h3><p>${f.sold?'Petals added to your game balance.':ready?'Keep this bloom, or let Pip take it home.':'Your seed is waking up. No wallet confirmation needed.'}</p><div class="flower-bottom"><b>${ready?amount(f.reward)+' ARCA':'Growing…'}</b>${f.sold?'<span>✓ In your game purse</span>':`<button class="button" data-sell="${f.id}" ${!ready||busy?'disabled':''}>${ready?'Sell to Pip':'A little patience…'}</button>`}</div></div></article>`;
  }).join('')||'<div class="empty-session"><span>✧</span><h3>Your little corner of magic.</h3><p>Choose a seed and potion to grow your first flower. Each bloom stays here until you choose to sell.</p></div>';
  if(markup!==lastFlowerMarkup){$('#flowers').innerHTML=markup;lastFlowerMarkup=markup;}
  const w=a?.withdrawals.find(w=>w.status==='pending');$('#pending-withdrawal').hidden=!w;
  if(w)$('#pending-withdrawal').innerHTML=`<b>${amount(w.amount)} ARCA reserved for your withdrawal</b><p>This amount is waiting for payment and cannot be spent in-game at the same time. If you declined MetaMask, retry it or recover it after the voucher expires and Sepolia finalizes.</p><button class="button" id="retry-withdraw" ${busy?'disabled':''}>Retry withdrawal ↗</button> <button class="text-button" id="release-withdraw" ${busy?'disabled':''}>Recover pending withdrawal</button>`;
  $('#history').innerHTML=a?.history.length?a.history.slice(0,12).map(h=>`<div class="activity"><span>${esc({grow:'Potion purchased & seed planted',sell:'Flower sold · game balance credited',deposit:'Deposit confirmed',withdraw:'Withdrawal reserved',paid:'ARCA paid to wallet',expired:'Pending withdrawal returned to game'}[h.kind]||h.kind)}<small>${new Date(h.at).toLocaleString()}</small></span><b>${['deposit','sell','expired'].includes(h.kind)?'+':'−'}${amount(h.amount)} ARCA</b>${h.hash?`<a href="https://sepolia.etherscan.io/tx/${h.hash}" target="_blank" rel="noreferrer">Receipt ↗</a>`:'<small>Saved game record</small>'}</div>`).join(''):'<p class="fine">Your deposits, potions, sales and withdrawals will appear here.</p>';
}
document.querySelectorAll('[data-seed]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.seed);render();});
$('#tier').onchange=e=>{selectedTier=Number(e.target.value);render();};$('#infusion').onchange=e=>{selectedInfusion=Number(e.target.value);render();};
document.querySelectorAll('[data-potion]').forEach(b=>b.onclick=()=>{selectedTier=Number(b.dataset.potion);$('#tier').value=String(selectedTier);render();});
function renderArtwork(){
  const key=[selected,selectedTier,selectedInfusion].join(':');if(key===lastArtSelection)return;lastArtSelection=key;
  clearTimeout(previewTimer);$('#growth-preview').hidden=true;$('#preview-growth').textContent='Preview growth ✧';
  $('#atlas-title').textContent='The many faces of '+SEEDS[selected].name+'.';
  $('#bloom-forms').innerHTML=RARITIES.map((r,i)=>`<article class="bloom-form" style="--rarity:${r.color}"><span class="form-rarity">${i===1?'Uncommon · Alternate color':r.label} · ${[75,20,4,1][i]}%</span><div class="form-art">${specimen(selected,i)}</div><h3>${FORMS[selected][i]}</h3><p>${[40,60,150,400][i]*2**selectedTier} ARCA · Pip’s offer</p></article>`).join('');
  document.querySelectorAll('[data-potion]').forEach(b=>{const i=Number(b.dataset.potion),yes=i===selectedTier;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));b.querySelector('.bottle-art').innerHTML=potionSVG(potion(i,selectedInfusion))+`<span class="bottle-seal">${['☽','✧','✦','♛'][i]}</span>`;b.querySelector('.potion-selection').textContent=yes?'Selected ✧':'Choose potion';});
}
$('#preview-growth').onclick=()=>{clearTimeout(previewTimer);const species=selected,infusion=selectedInfusion,tier=selectedTier;$('#growth-preview').hidden=false;$('#preview-growth').textContent='Replay growth ✧';$('#growth-preview-art').innerHTML=growingArt(species,1,infusion,tier);$('#growth-preview-copy').textContent='Preview only · a drop of magic awakens your seed…';previewTimer=setTimeout(()=>{$('#growth-preview-art').innerHTML=growingArt(species,2,infusion,tier);$('#growth-preview-copy').textContent='A tiny shoot reaches for the moonlight…';previewTimer=setTimeout(()=>{$('#growth-preview-art').innerHTML=specimen(species,0);$('#growth-preview-copy').textContent='Common bloom preview · actual rarity is revealed after planting. No ARCA was spent.';},2500);},2500);};
// These game actions deliberately have no wallet/provider dependency.
$('#grow').onclick=()=>action(async()=>{await gameAction('grow',{species:selected,tier:selectedTier,infusion:selectedInfusion});notify('Potion purchased from your game balance. Your seed is growing — no wallet transaction.');await refresh();$('#my-garden').scrollIntoView({behavior:'smooth'});});
$('#flowers').onclick=e=>{const b=e.target.closest('[data-sell]');if(!b)return;action(async()=>{const r=await gameAction('sell',{id:b.dataset.sell});$('#sale-choice').hidden=false;$('#sale-message').textContent=`+${amount(r.amount)} ARCA is now in your game purse. What would you like to do?`;notify(`Sold! +${amount(r.amount)} ARCA added to your game balance. Keep playing, or withdraw whenever you choose.`);await refresh();$('.pip-market').scrollIntoView({behavior:'smooth'});});};

let transferMode='deposit';
function openTransfer(mode){transferMode=mode;$('#transfer-dialog').showModal();$('#transfer-amount').value='';updateDialog();}
function updateDialog(){const withdraw=transferMode==='withdraw',eth=transferMode==='eth';$('#dialog-title').textContent=withdraw?'Take your petals home.':eth?'A little more magic.':'Bring your petals inside.';$('#dialog-copy').textContent=withdraw?'Choose how much game ARCA to send to your connected wallet. The rest stays ready for your next flower.':eth?'Buy ARCA directly into your game balance with Sepolia test ETH. One wallet transaction.':'Move existing wallet ARCA into your game balance. No new token purchase and no approval transaction.';$('#amount-label').firstChild.textContent=eth?'Amount in Sepolia ETH':'Amount in ARCA';$('#transfer-submit').textContent=withdraw?'Withdraw ARCA · MetaMask ↗':eth?'Top up game balance · MetaMask ↗':'Deposit ARCA · MetaMask ↗';$('#max').hidden=eth;$('#switch-deposit').hidden=withdraw;$('#switch-deposit').textContent=eth?'Use my existing ARCA instead':'Or top up using Sepolia ETH';$('#transfer-quote').textContent=eth?'0.001 Sepolia ETH → 100 game ARCA. This is not an ETH redemption service.':withdraw?`Available: ${amount(state?.account?.balance)} game ARCA.`:`Wallet balance: ${walletBalance===null?'refreshing…':amount(walletBalance)+' ARCA'}. Your existing tokens keep the same contract.`;}
$('#open-topup').onclick=()=>openTransfer('eth');$('#open-deposit').onclick=()=>openTransfer('deposit');$('#open-withdraw').onclick=$('#sale-withdraw').onclick=()=>openTransfer('withdraw');
$('#max').onclick=()=>$('#transfer-amount').value=amount(transferMode==='withdraw'?state.account.balance:walletBalance);
$('#transfer-amount').oninput=()=>{if(transferMode!=='eth')return;try{const received=quoteArca(parseEther($('#transfer-amount').value.trim()));$('#transfer-quote').textContent=`You receive ${amount(received)} ARCA in your game balance. One MetaMask transaction; network gas is extra. Existing wallet ARCA stays unchanged.`;}catch{$('#transfer-quote').textContent='Enter 0.0001 to 0.1 Sepolia ETH. 0.001 ETH = 100 game ARCA; network gas is extra.';}};
$('#switch-deposit').onclick=()=>{transferMode=transferMode==='eth'?'deposit':'eth';$('#transfer-amount').value='';updateDialog();};
function showReceipt(title,hash,copy){$('#receipt').hidden=false;$('#receipt').innerHTML=`<b>${esc(title)}</b><p>${esc(copy)}</p>${hash?`<a class="break" href="https://sepolia.etherscan.io/tx/${hash}" target="_blank" rel="noreferrer">${hash} ↗</a>`:''}`;}
function savePending(value){try{localStorage.setItem('arcana:settlement:pending',JSON.stringify(value));}catch{}}
async function verifyLater(path,body){for(let i=0;i<24;i++){try{return await api(path,body);}catch(e){if(!/pending|second Sepolia confirmation/i.test(e.message)||i===23)throw e;await new Promise(r=>setTimeout(r,3000));}}}
async function confirmDeposit(tx){savePending({kind:'deposit',hash:tx.hash,wallet:state.wallet});showReceipt('Deposit submitted',tx.hash,'Waiting for Sepolia confirmation. Do not send the same deposit again.');await verifyLater('deposit',{hash:tx.hash});showReceipt('Deposit confirmed',tx.hash,'ARCA is in your game balance. Potions, growth and sales now use this balance without wallet transactions.');await refresh();await readWallet();}
async function payWithdrawal(w){const s=await signer(),v=await api('withdraw/voucher',{nonce:w.nonce});const before=await new Contract(TOKEN,tokenAbi,s).balanceOf(state.wallet);const tx=await new Contract(state.vault,vaultArtifact.abi,s).withdraw(v.amount,v.nonce,v.deadline,v.signature);savePending({kind:'withdraw',hash:tx.hash,nonce:w.nonce,wallet:state.wallet});showReceipt('Withdrawal submitted',tx.hash,'Waiting for the actual ARCA transfer to your wallet.');await verifyLater('withdraw/reconcile',{nonce:w.nonce,hash:tx.hash});await readWallet();showReceipt('ARCA received by your wallet',tx.hash,`${amount(w.amount)} ARCA transferred. Wallet before: ${amount(before)} ARCA. Latest on-chain balance: ${walletBalance===null?'temporarily unavailable':amount(walletBalance)+' ARCA'}. Remaining game ARCA is still yours to play with.`);notify(`Withdrawal confirmed: ${amount(w.amount)} ARCA sent to your wallet.`);}
$('#transfer-submit').onclick=()=>action(async()=>{const n=parseEther($('#transfer-amount').value.trim());if(n<=0n)throw Error('Enter an amount greater than zero.');const mode=transferMode;if(mode==='withdraw'&&n>BigInt(state.account.balance))throw Error('Amount exceeds your game balance.');if(mode==='deposit'&&walletBalance!==null&&n>BigInt(walletBalance))throw Error('Amount exceeds your wallet ARCA.');if(mode==='eth'&&(n<100000000000000n||n>100000000000000000n))throw Error('Enter 0.0001 to 0.1 Sepolia ETH.');$('#transfer-dialog').close();if(mode==='withdraw'){await signer();const w=await gameAction('withdraw',{amount:n.toString()});await refresh();await payWithdrawal(w);}else{const s=await signer();const tx=mode==='eth'?await new Contract(state.vault,vaultArtifact.abi,s).depositEth({value:n}):await new Contract(TOKEN,tokenAbi,s).transfer(state.vault,n);await confirmDeposit(tx);}});
$('#pending-withdrawal').onclick=e=>{const w=state.account.withdrawals.find(w=>w.status==='pending');if(e.target.id==='retry-withdraw')action(()=>payWithdrawal(w));if(e.target.id==='release-withdraw')action(async()=>{await api('withdraw/reconcile',{nonce:w.nonce});notify('The unused withdrawal has been returned to your game balance.');});};
$('#recover').onclick=()=>action(async()=>{const hash=$('#recover-hash').value.trim(),kind=$('#recover-type').value;if(!/^0x[\da-f]{64}$/i.test(hash))throw Error('Enter the complete transaction hash.');if(kind==='deposit')await api('deposit',{hash});else{const w=state.account.withdrawals.find(w=>w.status==='pending');if(!w)throw Error('No pending withdrawal in this game account.');await api('withdraw/reconcile',{nonce:w.nonce,hash});}await readWallet();showReceipt('Transfer verified',hash,'The successful receipt has been checked and your balances synchronized.');notify('Receipt verified. Your balances are up to date.');});
$('#deploy-vault').onclick=()=>action(async()=>{if(!state.signer)throw Error('Server signing must be configured before deployment.');const value=parseEther($('#setup-funding').value);if(value<100000000000000n||value>100000000000000000n)throw Error('Choose 0.0001 to 0.1 Sepolia ETH for buyback reserves.');const q=await api('setup/quote',{amount:value.toString()});$('#setup-quote').textContent=`Reserve: ${amount(value)} ETH + maximum network fee: ${amount(q.maximumNetworkFee)} ETH. Maximum total: ${amount(q.total)} ETH. Wallet: ${amount(q.balance)} ETH. Quote at Sepolia block ${q.block}.`;if(!q.sufficient)throw Error('Not enough Sepolia ETH for this quote. Your existing ARCA is unchanged.');const s=await signer();notify(`Review in MetaMask: ${amount(value)} test ETH reserve + up to ${amount(q.maximumNetworkFee)} ETH network fee. Existing wallet ARCA is untouched.`);const c=await new ContractFactory(vaultArtifact.abi,vaultArtifact.bytecode,s).deploy(TOKEN,state.signer,{value,gasLimit:BigInt(q.gasLimit),maxFeePerGas:BigInt(q.maxFeePerGas),maxPriorityFeePerGas:BigInt(q.maxPriorityFeePerGas)});const address=await c.getAddress(),hash=c.deploymentTransaction().hash;$('#setup-address').value=address;$('#setup-hash').value=hash;savePending({kind:'setup',address,hash,wallet:state.wallet});showReceipt('Settlement deployment submitted',hash,'Waiting for confirmation and contract verification.');await verifyLater('setup',{address,hash});showReceipt('Settlement confirmed & activated',hash,'The deployed code and initial reserve were verified. Existing wallet ARCA is unchanged.');notify('Settlement activated. Deposit existing ARCA to start playing.');});
$('#register-vault').onclick=()=>action(async()=>{await api('setup',{address:$('#setup-address').value.trim(),hash:$('#setup-hash').value.trim()});showReceipt('Settlement confirmed & activated',$('#setup-hash').value.trim(),'The deployment and reserve have been verified.');notify('Settlement verified and activated.');});

try{const p=JSON.parse(localStorage.getItem('arcana:settlement:pending')||'null');if(p?.hash){$('#recover-hash').value=p.hash;$('#recover-type').value=p.kind==='withdraw'?'withdraw':'deposit';if(p.kind==='setup'){$('#setup-address').value=p.address;$('#setup-hash').value=p.hash;}}}catch{}
refresh().then(()=>{if(state?.wallet)return readWallet();});
setInterval(()=>{if(!busy&&document.visibilityState==='visible'&&state?.wallet)refresh();},3000);
